[build]
  command = "npm run build"
  publish = "out"

# Environment variables for build
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Basic redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force cache refresh with headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 