[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

[context.production.environment]
  NEXT_EXPORT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 