[build]
  # Simple build command that works from root directory
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/out"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://gorbagana-trash-tac-toe-backend.onrender.com/api/:splat"
  status = 200

# Cache busting headers for critical fixes
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0"
    X-Cache-Bust = "critical-fix-v1.0"
    X-Deployment-Time = "2025-01-29-19:15:00"

[[headers]]  
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0" 