[build]
  # Build from frontend directory  
  base = "frontend"
  command = "npm run build"
  publish = "out"
  
  [build.environment]
    # Skip Next.js plugin since we're using static export
    NETLIFY_NEXT_PLUGIN_SKIP = "true"
    # Ensure Next.js generates static export
    NEXT_TELEMETRY_DISABLED = "1"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://gorbagana-trash-tac-toe-backend.onrender.com/api/:splat"
  status = 200

# Cache busting headers for critical wallet conflict fixes
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0"
    X-Cache-Bust = "wallet-conflict-fix-v7.0"
    X-Deployment-Time = "2025-01-29-19:20:00"

[[headers]]  
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0" 