[build]
  # Build from root directory but target frontend
  command = "cd frontend && rm -rf node_modules && rm -rf package-lock.json && npm install --include=dev && npm install --save-dev tailwindcss@^3.3.0 autoprefixer@^10.4.14 postcss@^8.4.24 && rm -rf .next && rm -rf out && npm run build"
  publish = "frontend/out"

# ULTRA AGGRESSIVE CACHE CLEAR - v5.0
# Environment variables for build
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  CACHE_BUST_ID = "v5-ultra-aggressive-2025-01-29-1630"
  BUILD_TIMESTAMP = "1751204400000"
  FORCE_REBUILD = "true"
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-cache"
  CACHE_BUST = "v5.1-gorchain-fix-2025-01-29-16-55"
  BUILD_ID = "ultra-final-v5.1"

# NUCLEAR CACHE CLEAR - Force all files to reload
[[headers]]
  for = "/*"
  [headers.values]
    # ULTRA AGGRESSIVE CACHE CLEARING v5.0
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0"
    Pragma = "no-cache"
    Expires = "0"
    # Force new ETag
    ETag = "v5.1-gorchain-fix"
    # Custom headers for verification
    X-Cache-Bust = "v5.1-gorchain-fix-2025-01-29-16-55"
    X-Deployment-Time = "2025-01-29-16:55:00"
    X-RPC-Endpoint = "gorchain.wstf.io"

# Force JS files to reload
[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    X-Cache-Bust = "v5-js-reload"

# Basic redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force cache refresh with headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    # FORCE RELOAD OF ALL STATIC ASSETS
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "v5.1-static-bust"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# API redirect for backend
[[redirects]]
  from = "/api/*"
  to = "https://gorbagana-trash-tac-toe-backend.onrender.com/api/:splat"
  status = 200

# SPA fallback (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 